import { useEffect, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import Lenis from "lenis";
import { ArrowDownRight, ArrowUpRight, Menu, X } from "lucide-react";
import { portfolio, type Project } from "./data/portfolio";
import { GithubSection } from "./components/GithubSection";

const scrollTo = (id: string) => document.querySelector(id)?.scrollIntoView({ behavior: "smooth" });

function Reveal({ children }: { children: React.ReactNode }) { const reduce = useReducedMotion(); return <motion.div initial={reduce ? false : { opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .55, ease: "easeOut" }}>{children}</motion.div>; }

function LiveProjectLink({ project }: { project: Project }) { if (!project.links.live) return null; return <a className="text-link live-project-link" href={project.links.live} target="_blank" rel="noreferrer" aria-label={`Open ${project.title} live project in a new tab`}>LIVE PROJECT ↗</a>; }

function ProjectArt({ project, large = false }: { project: Project; large?: boolean }) { const category = project.platforms[0]?.type ?? "web"; const isNoBogey = project.slug === "nobogey-caddie-booking"; const hasCover = Boolean(project.cover); return <div className={`project-art project-art--${category} ${!hasCover ? "project-art--placeholder" : ""} ${large ? "project-art--large" : ""}`} style={!hasCover ? { background: "linear-gradient(135deg, #1d231a, #54733d)" } : undefined} aria-label={`${project.title} project cover`} role="img">{project.cover && <img src={project.cover} alt="" onError={(event) => { event.currentTarget.style.display = "none"; }} />}<div className="project-art__grid" /><span className="project-art__index">PROJECT_INDEX: {project.index}</span><span className="project-art__category">{project.categories.join(" / ")} / {project.year}</span>{!hasCover && <span className="project-art__placeholder-label">ETL PIPELINE<br />COVER IN PROGRESS</span>}<div className="project-art__shape" /><strong style={isNoBogey ? { background: "#0b0c09", border: "1px solid #c7f430", borderRadius: 10, boxShadow: "0 8px 22px rgba(0, 0, 0, .45)", color: "#c7f430", fontStyle: "italic", lineHeight: ".92", maxWidth: "calc(100% - 32px)", padding: "9px 13px" } : undefined}>{project.title}</strong></div>; }

function Header({ dark, toggleTheme }: { dark: boolean; toggleTheme: () => void }) { const [open, setOpen] = useState(false); const links = [["WORK", "#work"], ["EXPERIENCE", "#experience"], ["STACK", "#stack"], ["ABOUT", "#about"]] as const; const go = (id: string) => { setOpen(false); scrollTo(id); }; return <header className="site-header"><button className="brand" onClick={() => go("#top")} aria-label="Back to top">{portfolio.shortName}</button><nav className="desktop-nav" aria-label="Primary navigation">{links.map(([label, target]) => <button key={target} onClick={() => go(target)}>{label}</button>)}<a href={portfolio.resume} target="_blank" rel="noreferrer">RÉSUMÉ ↗</a></nav><span className="header-status mono"><i />AVAILABLE</span><button className="theme-toggle" type="button" onClick={toggleTheme} aria-label={`Switch to ${dark ? "light" : "dark"} mode`} aria-pressed={dark}><span aria-hidden="true">{dark ? "☼" : "◐"}</span>{dark ? "LIGHT" : "DARK"}</button><button className="menu-button" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X size={18} /> : <Menu size={18} />}<span>{open ? "CLOSE" : "MENU"}</span></button><AnimatePresence>{open && <motion.nav className="mobile-nav" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} aria-label="Mobile navigation">{links.map(([label, target], i) => <motion.button key={target} onClick={() => go(target)} initial={{ y: 24, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: i * .04 }}><small>{String(i + 1).padStart(2, "0")}</small>{label}</motion.button>)}<a href={portfolio.resume} target="_blank" rel="noreferrer">RÉSUMÉ ↗</a></motion.nav>}</AnimatePresence></header>; }

function Hero({ dark }: { dark: boolean }) { const reduce = useReducedMotion(); const [pixelMode, setPixelMode] = useState(true); const [pixelating, setPixelating] = useState(false); const portrait = pixelMode ? `${import.meta.env.BASE_URL}images/me-pic-pixel.png` : `${import.meta.env.BASE_URL}images/me-pic.jpg`; const portraitFilter = dark ? "grayscale(1) contrast(1.2) brightness(.9)" : "grayscale(0)"; const togglePortrait = () => { if (!pixelMode && !reduce) setPixelating(true); setPixelMode(value => !value); }; return <section id="top" className="hero"><div className="hero__meta mono"><span>01 / BUILDER</span><span><i className="availability-dot" />OPEN TO OPPORTUNITIES</span></div><div className="hero__title">{portfolio.headline.map((line, i) => <motion.h1 key={line} initial={reduce ? false : { y: 65, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: .7, delay: i * .08 }}>{line}</motion.h1>)}<button type="button" className={`hero__portrait ${pixelMode ? "hero__portrait--pixel" : ""}`} onClick={togglePortrait} aria-pressed={pixelMode} aria-label={pixelMode ? "Show Francis Dreu photo portrait" : "Show Francis Dreu pixel portrait"}><AnimatePresence initial={false} mode="wait"><motion.img key={portrait} src={portrait} alt="" initial={reduce ? false : { opacity: 0, scale: 1.1, filter: portraitFilter }} animate={{ opacity: 1, scale: 1, filter: portraitFilter }} exit={reduce ? undefined : { opacity: 0, scale: .92, filter: portraitFilter }} transition={{ duration: reduce ? 0 : .36, ease: "easeOut" }} /></AnimatePresence>{pixelating && <i className="hero__pixel-transition" aria-hidden="true" onAnimationEnd={() => setPixelating(false)} />}</button></div><div className="hero__bottom"><div><p>{portfolio.intro}</p><div className="hero__actions"><button className="text-link" onClick={() => scrollTo("#work")}>VIEW MY WORK <ArrowDownRight /></button><a className="text-link" href={portfolio.resume} target="_blank" rel="noreferrer">DOWNLOAD RÉSUMÉ <ArrowDownRight /></a></div></div></div><span className="hero__active mono">BUILD → MEASURE → REFINE → REPEAT</span></section>; }

function About() { return <section id="about" className="about section-shell"><div className="section-label mono">06 / ABOUT <span>WHY I BUILD</span></div><div className="about__grid"><h2>I WORK BETWEEN<br />DATA, DESIGN<br />AND <em>DEVELOPMENT.</em></h2><div><p className="body-large">{portfolio.bio}</p><p className="body-copy">{portfolio.aboutDetail}</p><div className="fact-grid">{portfolio.stats.map(stat => <div key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</div></div></div></section>; }

function Expertise() { const [active, setActive] = useState(0); const reduce = useReducedMotion(); const total = portfolio.roles.length; const move = (direction: 1 | -1) => setActive(current => (current + direction + total) % total); useEffect(() => { if (reduce) return; const timer = window.setInterval(() => move(1), 10_000); return () => window.clearInterval(timer); }, [reduce]); return <section id="expertise" className="expertise"><div className="section-shell"><div className="section-label mono">FOUR MODES OF THINKING <span>{String(active + 1).padStart(2, "0")} — {String(total).padStart(2, "0")}</span></div></div><div className="expertise__carousel" role="region" aria-roledescription="carousel" aria-label="Areas of expertise"><div className="expertise__rail" style={{ transform: `translateX(-${active * 25}%)` }}>{portfolio.roles.map((role, i) => <article key={role.title} className={`expertise-card expertise-card--${role.slug}`} aria-hidden={i !== active}><div className="mono"><span>MODE {String(i + 1).padStart(2, "0")}</span><span>{role.title}</span></div><div className="expertise-card__motif" aria-hidden="true"><i /><i /><i /></div><h2>{role.headline.map(line => <span key={line}>{line}</span>)}</h2><p>{role.description}</p><div className="skill-cloud">{role.skills.slice(0, 6).map(skill => <span key={skill}>{skill}</span>)}</div><button className="text-link" onClick={() => scrollTo("#work")}>EXPLORE {role.short} <ArrowDownRight /></button></article>)}</div><div className="expertise__controls"><button type="button" onClick={() => move(-1)} aria-label="Previous expertise area">← PREVIOUS</button><div>{portfolio.roles.map((role, i) => <button type="button" key={role.slug} className={i === active ? "active" : ""} onClick={() => setActive(i)} aria-label={`Show ${role.title}`} aria-pressed={i === active} />)}</div><button type="button" onClick={() => move(1)} aria-label="Next expertise area">NEXT →</button></div></div></section>; }

function Work({ open }: { open: (project: Project) => void }) {
  const [active, setActive] = useState(0);
  const reduce = useReducedMotion();
  const total = portfolio.projects.length;
  const project = portfolio.projects[active];
  const move = (direction: 1 | -1) => setActive(current => (current + direction + total) % total);

  useEffect(() => {
    if (reduce || total < 2) return;
    const timer = window.setInterval(() => move(1), 9_000);
    return () => window.clearInterval(timer);
  }, [reduce, total]);

  return <section id="work" className="work section-shell"><div className="section-label mono">02 / SELECTED WORK <span>{String(active + 1).padStart(2, "0")} — {String(total).padStart(2, "0")}</span></div><div className="work__head"><h2>WORK WITH<br /><em>CONTEXT.</em></h2><p className="body-copy">Selected work across data systems, mobile products, and web experiences — with the decisions and implementation context behind each one.</p></div><div className="work-carousel" role="region" aria-roledescription="carousel" aria-label="Selected projects"><AnimatePresence mode="wait" initial={false}><motion.article key={project.slug} className="work-project work-project--carousel" initial={reduce ? false : { opacity: 0, x: 40 }} animate={{ opacity: 1, x: 0 }} exit={reduce ? undefined : { opacity: 0, x: -40 }} transition={{ duration: .42, ease: "easeOut" }}><button className="work-project__visual" type="button" onClick={() => open(project)}><ProjectArt project={project} /><span>OPEN CASE STUDY →</span></button><div className="work-project__content"><div className="mono"><span>{project.type}</span><span>{project.year}</span></div><h3>{project.title}</h3><p>{project.tagline}</p><div className="project-tags">{project.technologies.map(technology => <span key={technology}>{technology}</span>)}</div><div className="work-project__actions"><button className="text-link" type="button" onClick={() => open(project)}>VIEW CASE STUDY <ArrowDownRight /></button><LiveProjectLink project={project} /></div></div></motion.article></AnimatePresence><div className="work-carousel__controls"><button type="button" onClick={() => move(-1)} aria-label="Previous project">← PREVIOUS</button><div>{portfolio.projects.map((item, index) => <button type="button" key={item.slug} className={index === active ? "active" : ""} onClick={() => setActive(index)} aria-label={`Show ${item.title}`} aria-pressed={index === active} />)}</div><button type="button" onClick={() => move(1)} aria-label="Next project">NEXT →</button></div></div></section>;
}

function Skills() {
  const groups = Object.entries(portfolio.skillGroups);
  const firstRow = groups.filter(([group]) => group === "WEB" || group === "MOBILE" || group === "AI TOOLS").flatMap(([, skills]) => skills);
  const secondRow = groups.filter(([group]) => group === "DATA" || group === "DESIGN" || group === "TOOLS").flatMap(([, skills]) => skills);
  const Marquee = ({ skills, reverse = false }: { skills: string[]; reverse?: boolean }) => <div className={`skill-marquee ${reverse ? "skill-marquee--reverse" : ""}`}><div>{[...skills, ...skills].map((skill, index) => <span key={`${skill}-${index}`}>{skill}<b>•</b></span>)}</div></div>;

  return <section id="stack" className="skills-section section-shell"><div className="section-label mono">05 / TECH STACK <span>TOOLS THROUGHOUT THE LOOP</span></div><h2>TOOLS I USE<br />TO TURN IDEAS<br /><em>INTO PRODUCTS.</em></h2><div className="skill-marquees" aria-label="Technology stack"><Marquee skills={firstRow} /><Marquee skills={secondRow} reverse /></div><div className="skills-grid">{groups.map(([group, skills]) => <article key={group}><span className="mono">{group}</span><p>{skills.join("  /  ")}</p></article>)}</div></section>;
}
function Experience() { const reduce = useReducedMotion(); return <section id="experience" className="experience section-shell"><div className="experience__head"><div className="section-label mono">04 / EXPERIENCE <span>CHALLENGE → CONTRIBUTION → IMPACT</span></div><h2>WORK THAT<br /><em>MOVES FORWARD.</em></h2></div><div className="experience__timeline">{portfolio.experience.map((item, i) => <motion.article key={`${item.period}-${item.role}`} initial={reduce ? false : { opacity: 0, x: -46 }} whileInView={{ opacity: 1, x: 0 }} whileHover={reduce ? undefined : { x: 12 }} viewport={{ once: true, amount: .35 }} transition={{ duration: .55, delay: reduce ? 0 : i * .14, ease: "easeOut" }}><span className="mono">{item.period}</span><div><h3>{item.role}</h3><strong>{item.organization}</strong><p>{item.description}</p></div></motion.article>)}</div></section>; }

function Contact() {
  const sessionKey = "portfolio-contact-submitted";
  const [submitted, setSubmitted] = useState(() => sessionStorage.getItem(sessionKey) === "true");
  const [status, setStatus] = useState<"idle" | "sending" | "error">("idle");
  const [errors, setErrors] = useState<Record<string, string>>({});

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (submitted || status === "sending") return;

    const data = new FormData(event.currentTarget);
    const name = String(data.get("name") ?? "");
    const email = String(data.get("email") ?? "");
    const message = String(data.get("message") ?? "");
    const wordCount = message.trim() ? message.trim().split(/\s+/).length : 0;
    const nextErrors: Record<string, string> = {};

    if (name.trim().split(/\s+/).filter(Boolean).length < 2) nextErrors.name = "Enter your first and last name.";
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) nextErrors.email = "Enter a valid email address.";
    if (wordCount < 10) nextErrors.message = "Your message needs at least 10 words.";
    if (wordCount > 150) nextErrors.message = "Your message must be 150 words or fewer.";

    setErrors(nextErrors);
    if (Object.keys(nextErrors).length > 0) return;

    data.append("_subject", `Portfolio inquiry from ${name}`);
    setStatus("sending");

    try {
      const response = await fetch("https://formspree.io/f/mqpklblz", {
        method: "POST",
        body: data,
        headers: { Accept: "application/json" },
      });

      if (!response.ok) throw new Error("Formspree submission failed");
      sessionStorage.setItem(sessionKey, "true");
      setSubmitted(true);
    } catch {
      setStatus("error");
    }
  }

  return <section id="contact" className="contact"><div className="section-label mono">CONTACT / 08 <span>LET'S MAKE IT USEFUL</span></div><h2>LET'S BUILD<br />SOMETHING<br /><em>USEFUL.</em></h2><div className="contact__grid"><div className="contact-links"><a href={`mailto:${portfolio.email}`}>EMAIL <span>{portfolio.email}</span><ArrowUpRight /></a><a href={`tel:${portfolio.phone}`}>PHONE <span>{portfolio.phone}</span><ArrowUpRight /></a><a href={portfolio.github} target="_blank" rel="noreferrer">GITHUB <span>OPEN PROFILE</span><ArrowUpRight /></a><a href={portfolio.linkedin} target="_blank" rel="noreferrer">LINKEDIN <span>CONNECT</span><ArrowUpRight /></a></div><form noValidate onSubmit={submit}><label>FULL NAME<input required name="name" aria-invalid={Boolean(errors.name)} aria-describedby={errors.name ? "contact-name-error" : undefined} placeholder="[YOUR FULL NAME]" /></label>{errors.name && <p id="contact-name-error" className="contact-form-error">{errors.name}</p>}<label>EMAIL<input required name="email" type="email" aria-invalid={Boolean(errors.email)} aria-describedby={errors.email ? "contact-email-error" : undefined} placeholder="[YOUR EMAIL]" /></label>{errors.email && <p id="contact-email-error" className="contact-form-error">{errors.email}</p>}<label>MESSAGE<textarea required name="message" rows={3} aria-invalid={Boolean(errors.message)} aria-describedby={errors.message ? "contact-message-error" : "contact-message-hint"} placeholder="[TELL ME ABOUT YOUR PROJECT]" /></label>{errors.message ? <p id="contact-message-error" className="contact-form-error">{errors.message}</p> : <p id="contact-message-hint" className="contact-form-hint">10–150 words</p>}<button type="submit" disabled={submitted || status === "sending"}>{submitted ? "MESSAGE SENT — ONE PER SESSION" : status === "sending" ? "SENDING…" : "SEND MESSAGE →"}</button><small>{submitted ? "Thanks — your message has been sent." : status === "error" ? "Message could not be sent. Please try again." : "Your message will be sent directly to Francis."}</small></form></div></section>;
}

function CaseStudy({ project, close }: { project: Project; close: () => void }) { return <motion.main className="case-study" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><header><button className="brand" onClick={close}>← {portfolio.shortName}</button><button className="text-link" onClick={close}>BACK TO WORK</button></header><section className="case-study__hero"><div className="section-label mono">{project.categories.join(" / ")} / {project.year} <span>CASE STUDY / {project.index}</span></div><h1>{project.title}</h1><p>{project.description}</p><ProjectArt project={project} large /></section><section className="case-study__details">{[["01 — OVERVIEW", project.caseStudy.overview], ["02 — PROBLEM", project.caseStudy.problem], ["03 — APPROACH", project.caseStudy.approach], ["04 — SOLUTION", project.caseStudy.solution], ["05 — OUTCOME", project.caseStudy.outcome]].map(([label, body]) => <article key={label}><span className="mono">{label}</span><p>{body}</p></article>)}<article><span className="mono">06 — TECHNOLOGIES</span><p>{project.technologies.join(" / ")}</p></article></section><footer><button onClick={close}>← ALL WORK</button>{project.links.github && <a href={project.links.github} target="_blank" rel="noreferrer">GITHUB ↗</a>}<LiveProjectLink project={project} /></footer></motion.main>; }

export default function App() { const [activeProject, setActiveProject] = useState<Project | null>(null); const [dark, setDark] = useState(() => localStorage.getItem("portfolio-theme") === "dark" || (!localStorage.getItem("portfolio-theme") && window.matchMedia("(prefers-color-scheme: dark)").matches)); useEffect(() => { const lenis = new Lenis({ autoRaf: true, duration: 1.1, smoothWheel: true, syncTouch: false }); return () => lenis.destroy(); }, []); useEffect(() => { document.documentElement.classList.toggle("theme-dark", dark); localStorage.setItem("portfolio-theme", dark ? "dark" : "light"); }, [dark]); useEffect(() => { const slug = window.location.pathname.split("/").pop(); if (window.location.pathname.startsWith("/work/")) setActiveProject(portfolio.projects.find(project => project.slug === slug) ?? null); }, []); const open = (project: Project) => { window.history.pushState({}, "", `/work/${project.slug}`); setActiveProject(project); window.scrollTo(0, 0); }; const close = () => { window.history.pushState({}, "", "/"); setActiveProject(null); }; return <AnimatePresence mode="wait">{activeProject ? <CaseStudy key="case-study" project={activeProject} close={close} /> : <motion.main key="home" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><Header dark={dark} toggleTheme={() => setDark(value => !value)} /><Hero dark={dark} /><Reveal><Work open={open} /></Reveal><Reveal><Experience /></Reveal><Reveal><Skills /></Reveal><Reveal><About /></Reveal><Reveal><GithubSection username={portfolio.githubUsername} /></Reveal><Reveal><Contact /></Reveal><footer className="site-footer"><strong>Built, measured, refined, and shipped by Francis Dreu.</strong><span><a href={portfolio.github} target="_blank" rel="noreferrer">GITHUB ↗</a><a href={portfolio.linkedin} target="_blank" rel="noreferrer">LINKEDIN ↗</a><a href={`mailto:${portfolio.email}`}>EMAIL ↗</a></span><button onClick={() => scrollTo("#top")}>BACK TO TOP ↑</button><span>{portfolio.version} · © {new Date().getFullYear()}</span></footer></motion.main>}</AnimatePresence>; }
