import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { ArrowDownRight, ArrowUpRight, Menu, X } from "lucide-react";
import { portfolio, type Project } from "./data/portfolio";
import { GithubSection } from "./components/GithubSection";

type Filter = "all" | Project["category"];
const filters: { label: string; value: Filter }[] = [{ label: "All", value: "all" }, { label: "Data", value: "data" }, { label: "Design", value: "ui" }, { label: "Mobile", value: "mobile" }, { label: "Web", value: "web" }];
const scrollTo = (id: string) => document.querySelector(id)?.scrollIntoView({ behavior: "smooth" });

function Reveal({ children }: { children: React.ReactNode }) { const reduce = useReducedMotion(); return <motion.div initial={reduce ? false : { opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .55, ease: "easeOut" }}>{children}</motion.div>; }

function ProjectArt({ project, large = false }: { project: Project; large?: boolean }) { return <div className={`project-art project-art--${project.category} ${large ? "project-art--large" : ""}`} aria-label={`${project.title} image placeholder`} role="img">{project.image && <img src={project.image} alt="" onError={(event) => { event.currentTarget.style.display = "none"; }} />}<div className="project-art__grid" /><span className="project-art__index">PROJECT_INDEX: {project.index}</span><span className="project-art__category">{project.category.toUpperCase()} / {project.year}</span><div className="project-art__shape" /><strong>{project.image ? project.title : "ADD PROJECT IMAGE"}</strong></div>; }

function Header({ dark, toggleTheme }: { dark: boolean; toggleTheme: () => void }) { const [open, setOpen] = useState(false); const links = [["ABOUT", "#about"], ["WORK", "#work"], ["EXPERTISE", "#expertise"], ["EXPERIENCE", "#experience"], ["GITHUB", "#github"], ["CONTACT", "#contact"]] as const; const go = (id: string) => { setOpen(false); scrollTo(id); }; return <header className="site-header"><button className="brand" onClick={() => go("#top")} aria-label="Back to top">{portfolio.shortName}<sup>®</sup></button><nav className="desktop-nav" aria-label="Primary navigation">{links.map(([label, target]) => <button key={target} onClick={() => go(target)}>{label}</button>)}<a href={portfolio.resume} target="_blank" rel="noreferrer">RESUME ↗</a></nav><button className="theme-toggle" type="button" onClick={toggleTheme} aria-label={`Switch to ${dark ? "light" : "dark"} mode`} aria-pressed={dark}><span aria-hidden="true">{dark ? "☼" : "◐"}</span>{dark ? "LIGHT" : "DARK"}</button><button className="menu-button" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X size={18} /> : <Menu size={18} />}<span>{open ? "CLOSE" : "MENU"}</span></button><AnimatePresence>{open && <motion.nav className="mobile-nav" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} aria-label="Mobile navigation">{links.map(([label, target], i) => <motion.button key={target} onClick={() => go(target)} initial={{ y: 24, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: i * .04 }}><small>{String(i + 1).padStart(2, "0")}</small>{label}</motion.button>)}</motion.nav>}</AnimatePresence></header>; }

function Hero() { const reduce = useReducedMotion(); const [mode, setMode] = useState(0); useEffect(() => { const timer = window.setInterval(() => setMode(value => (value + 1) % portfolio.roles.length), 4000); return () => window.clearInterval(timer); }, []); const active = portfolio.roles[mode]; return <section id="top" className={`hero mode-${mode + 1}`}><div className="hero__meta mono"><span>BASED IN {portfolio.location}</span><span>2026 — AVAILABLE FOR {portfolio.availability}</span></div><div className="hero__title">{portfolio.headline.map((line, i) => <motion.h1 key={line} initial={reduce ? false : { y: 65, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: .7, delay: i * .08 }}>{line}</motion.h1>)}<div className="hero__portrait"><img src={`${import.meta.env.BASE_URL}images/me-pic.jpg`} alt={`${portfolio.name} portrait`} /></div></div><div className="hero__bottom"><p>{portfolio.intro}</p><div className="mode-selector">{portfolio.roles.map((role, i) => <button key={role.title} className={i === mode ? "active" : ""} onClick={() => setMode(i)}><small>MODE 0{i + 1}</small>{role.short}</button>)}</div><button className="text-link" onClick={() => scrollTo("#work")}>VIEW MY WORK <ArrowDownRight /></button></div><span className="hero__active mono">ACTIVE MODE / {active.title}</span></section>; }

function About() { return <section id="about" className="about section-shell"><div className="section-label mono">ABOUT / 01 <span>00.01 / INTRODUCTION</span></div><div className="about__grid"><h2>I WORK BETWEEN<br />DATA, DESIGN<br />AND <em>DEVELOPMENT.</em></h2><div><p className="body-large">{portfolio.bio}</p><p className="body-copy">{portfolio.aboutDetail}</p><div className="fact-grid">{portfolio.stats.map(stat => <div key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</div></div></div></section>; }

function Expertise() { const [active, setActive] = useState(0); const reduce = useReducedMotion(); const total = portfolio.roles.length; const move = (direction: 1 | -1) => setActive(current => (current + direction + total) % total); useEffect(() => { if (reduce) return; const timer = window.setInterval(() => move(1), 10_000); return () => window.clearInterval(timer); }, [reduce]); return <section id="expertise" className="expertise"><div className="section-shell"><div className="section-label mono">FOUR MODES OF THINKING <span>{String(active + 1).padStart(2, "0")} — {String(total).padStart(2, "0")}</span></div></div><div className="expertise__carousel" role="region" aria-roledescription="carousel" aria-label="Areas of expertise"><div className="expertise__rail" style={{ transform: `translateX(-${active * 25}%)` }}>{portfolio.roles.map((role, i) => <article key={role.title} className={`expertise-card expertise-card--${role.slug}`} aria-hidden={i !== active}><div className="mono"><span>MODE {String(i + 1).padStart(2, "0")}</span><span>{role.title}</span></div><div className="expertise-card__motif" aria-hidden="true"><i /><i /><i /></div><h2>{role.headline.map(line => <span key={line}>{line}</span>)}</h2><p>{role.description}</p><div className="skill-cloud">{role.skills.slice(0, 6).map(skill => <span key={skill}>{skill}</span>)}</div><button className="text-link" onClick={() => scrollTo("#work")}>EXPLORE {role.short} <ArrowDownRight /></button></article>)}</div><div className="expertise__controls"><button type="button" onClick={() => move(-1)} aria-label="Previous expertise area">← PREVIOUS</button><div>{portfolio.roles.map((role, i) => <button type="button" key={role.slug} className={i === active ? "active" : ""} onClick={() => setActive(i)} aria-label={`Show ${role.title}`} aria-pressed={i === active} />)}</div><button type="button" onClick={() => move(1)} aria-label="Next expertise area">NEXT →</button></div></div></section>; }

function Work({ openProject }: { openProject: (project: Project) => void }) { const [filter, setFilter] = useState<Filter>("all"); const reduce = useReducedMotion(); const projects = useMemo(() => portfolio.projects.filter(project => filter === "all" || project.category === filter), [filter]); return <section id="work" className="work section-shell"><div className="work__head"><div><div className="section-label mono">SELECTED WORK <span>PROJECT ARCHIVE</span></div><h2>Evidence in<br /><em>every mode.</em></h2></div><div className="work__filters" aria-label="Filter projects">{filters.map(option => <button key={option.value} className={filter === option.value ? "active" : ""} onClick={() => setFilter(option.value)}>{option.label}</button>)}</div></div><div className="project-list">{projects.map((project, i) => <motion.article className={`work-project work-project--${i % 2}`} key={project.slug} initial={reduce ? false : { opacity: 0, y: 54 }} whileInView={{ opacity: 1, y: 0 }} whileHover={reduce ? undefined : { y: -8 }} viewport={{ once: true, amount: .18 }} transition={{ duration: .6, delay: reduce ? 0 : i * .08, ease: "easeOut" }}><button className="work-project__visual" onClick={() => openProject(project)}><ProjectArt project={project} /><span>VIEW CASE STUDY ↗</span></button><div className="work-project__content"><div className="mono"><span>{project.index}</span><span>{project.category.toUpperCase()} / {project.year}</span></div><h3>{project.title}</h3><p>{project.description}</p><div className="project-tags">{project.technologies.map(technology => <span key={technology}>{technology}</span>)}</div><button className="text-link" onClick={() => openProject(project)}>VIEW CASE STUDY <ArrowUpRight /></button></div></motion.article>)}</div></section>; }

function Skills() { const reduce = useReducedMotion(); return <section className="skills-section section-shell"><div className="section-label mono">TOOLS / TECHNOLOGY STACK</div><h2>TOOLS I USE<br />TO TURN IDEAS<br /><em>INTO PRODUCTS.</em></h2><div className="skills-grid">{Object.entries(portfolio.skillGroups).map(([group, skills], i) => <motion.article key={group} initial={reduce ? false : { opacity: 0, x: -22 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: .3 }} transition={{ duration: .42, delay: reduce ? 0 : i * .07 }}><span className="mono">{group}</span><p>{skills.join("  /  ")}</p></motion.article>)}</div></section>; }
function Experience() { const reduce = useReducedMotion(); return <section id="experience" className="experience section-shell"><div className="experience__head"><div className="section-label mono">EXPERIENCE / TIMELINE <span>WHERE I'VE CONTRIBUTED</span></div><h2>WORK THAT<br /><em>MOVES FORWARD.</em></h2></div><div className="experience__timeline">{portfolio.experience.map((item, i) => <motion.article key={`${item.period}-${item.role}`} initial={reduce ? false : { opacity: 0, x: -46 }} whileInView={{ opacity: 1, x: 0 }} whileHover={reduce ? undefined : { x: 12 }} viewport={{ once: true, amount: .35 }} transition={{ duration: .55, delay: reduce ? 0 : i * .14, ease: "easeOut" }}><span className="mono">{item.period}</span><div><h3>{item.role}</h3><strong>{item.organization}</strong><p>{item.description}</p></div></motion.article>)}</div></section>; }

function Contact() { const [status, setStatus] = useState<"idle" | "sending" | "success">("idle"); function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("sending"); window.setTimeout(() => setStatus("success"), 650); } return <section id="contact" className="contact"><div className="section-label mono">CONTACT / 08 <span>LET'S MAKE IT USEFUL</span></div><h2>LET'S BUILD<br />SOMETHING<br /><em>USEFUL.</em></h2><div className="contact__grid"><div className="contact-links"><a href={`mailto:${portfolio.email}`}>EMAIL <span>{portfolio.email}</span><ArrowUpRight /></a><a href={`tel:${portfolio.phone}`}>PHONE <span>{portfolio.phone}</span><ArrowUpRight /></a><a href={portfolio.github} target="_blank" rel="noreferrer">GITHUB <span>OPEN PROFILE</span><ArrowUpRight /></a><a href={portfolio.linkedin} target="_blank" rel="noreferrer">LINKEDIN <span>CONNECT</span><ArrowUpRight /></a></div><form onSubmit={submit}><label>NAME<input required placeholder="[YOUR NAME]" /></label><label>EMAIL<input required type="email" placeholder="[YOUR EMAIL]" /></label><label>MESSAGE<textarea required rows={3} placeholder="[TELL ME ABOUT YOUR PROJECT]" /></label><button type="submit" disabled={status === "sending"}>{status === "sending" ? "SENDING…" : status === "success" ? "MESSAGE READY — CHECK EMAIL ↗" : "SEND MESSAGE →"}</button><small>This demo form has no email provider connected yet.</small></form></div></section>; }

function CaseStudy({ project, close }: { project: Project; close: () => void }) { return <motion.main className="case-study" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><header><button className="brand" onClick={close}>← {portfolio.shortName}</button><button className="text-link" onClick={close}>BACK TO WORK</button></header><section className="case-study__hero"><div className="section-label mono">{project.category.toUpperCase()} / {project.year} <span>CASE STUDY / {project.index}</span></div><h1>{project.title}</h1><p>{project.description}</p><ProjectArt project={project} large /></section><section className="case-study__details">{[["01 — OVERVIEW", project.overview], ["02 — PROBLEM", project.problem], ["03 — APPROACH", project.approach], ["04 — SOLUTION", project.solution]].map(([label, body]) => <article key={label}><span className="mono">{label}</span><p>{body}</p></article>)}<article><span className="mono">05 — TECHNOLOGIES</span><p>{project.technologies.join(" / ")}</p></article></section><footer><button onClick={close}>← ALL WORK</button><a href={project.github || "#"} target="_blank" rel="noreferrer">GITHUB ↗</a><a href={project.liveUrl || "#"} target="_blank" rel="noreferrer">LIVE PROJECT ↗</a></footer></motion.main>; }

const onboardingSteps = [
  { eyebrow: "01 / WELCOME", title: "START HERE.", body: "This short guide highlights the key parts of my portfolio.", target: "#top" },
  { eyebrow: "02 / EXPLORE", title: "CHOOSE A MODE.", body: "Use the mode selector to explore how I approach data, design, mobile, and web work.", target: "#top" },
  { eyebrow: "03 / WORK", title: "BROWSE THE WORK.", body: "Filter the project archive, then open any project to view its case study.", target: "#work" },
  { eyebrow: "04 / CONNECT", title: "LET'S TALK.", body: "When you have a project in mind, use the contact section to get in touch.", target: "#contact" },
];

function Onboarding({ complete }: { complete: () => void }) {
  const [step, setStep] = useState(0);
  const current = onboardingSteps[step];
  const move = (nextStep: number) => { setStep(nextStep); scrollTo(onboardingSteps[nextStep].target); };
  return <motion.aside className="onboarding" role="dialog" aria-modal="true" aria-labelledby="onboarding-title" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><div className="onboarding__scrim" /><motion.div className="onboarding__panel" initial={{ y: 24, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 24, opacity: 0 }}><div className="onboarding__top mono"><span>{current.eyebrow}</span><span>{String(step + 1).padStart(2, "0")} / {String(onboardingSteps.length).padStart(2, "0")}</span></div><div><h2 id="onboarding-title">{current.title}</h2><p>{current.body}</p></div><div className="onboarding__progress" aria-label={`Step ${step + 1} of ${onboardingSteps.length}`}>{onboardingSteps.map((item, index) => <i key={item.eyebrow} className={index <= step ? "active" : ""} />)}</div><div className="onboarding__actions"><button className="onboarding__skip" onClick={complete}>SKIP TOUR</button><div>{step > 0 && <button className="onboarding__back" onClick={() => move(step - 1)}>BACK</button>}<button className="onboarding__next" onClick={() => step === onboardingSteps.length - 1 ? complete() : move(step + 1)}>{step === onboardingSteps.length - 1 ? "START EXPLORING" : "NEXT"} →</button></div></div></motion.div></motion.aside>;
}

export default function App() { const [activeProject, setActiveProject] = useState<Project | null>(null); const [dark, setDark] = useState(() => localStorage.getItem("portfolio-theme") === "dark" || (!localStorage.getItem("portfolio-theme") && window.matchMedia("(prefers-color-scheme: dark)").matches)); const [showOnboarding, setShowOnboarding] = useState(() => localStorage.getItem("portfolio-onboarding-complete") !== "true"); useEffect(() => { document.documentElement.classList.toggle("theme-dark", dark); localStorage.setItem("portfolio-theme", dark ? "dark" : "light"); }, [dark]); useEffect(() => { const slug = window.location.pathname.split("/").pop(); if (window.location.pathname.startsWith("/work/")) setActiveProject(portfolio.projects.find(project => project.slug === slug) ?? null); }, []); const open = (project: Project) => { window.history.pushState({}, "", `/work/${project.slug}`); setActiveProject(project); window.scrollTo(0, 0); }; const close = () => { window.history.pushState({}, "", "/"); setActiveProject(null); }; const completeOnboarding = () => { localStorage.setItem("portfolio-onboarding-complete", "true"); setShowOnboarding(false); }; return <AnimatePresence mode="wait">{activeProject ? <CaseStudy key="case-study" project={activeProject} close={close} /> : <motion.main key="home" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><Header dark={dark} toggleTheme={() => setDark(value => !value)} /><Hero /><Reveal><About /></Reveal><Reveal><Expertise /></Reveal><Work openProject={open} /><Reveal><GithubSection username={portfolio.githubUsername} /></Reveal><Reveal><Skills /></Reveal><Reveal><Experience /></Reveal><Reveal><Contact /></Reveal><footer className="site-footer"><strong>{portfolio.name}</strong><span>DATA / DESIGN / MOBILE / WEB</span><button onClick={() => scrollTo("#top")}>BACK TO TOP ↑</button><span>© {new Date().getFullYear()}</span></footer><AnimatePresence>{showOnboarding && <Onboarding complete={completeOnboarding} />}</AnimatePresence></motion.main>}</AnimatePresence>; }
